#!/usr/bin/env bash

# dig the World wide web
# dig is a flexible tool for interrogating DNS name servers. 
# It performs DNS lookups and displays the answers that are returned from the name server(s) that were queried.
# Most DNS administrators use dig to troubleshoot DNS problems because of its flexibility, ease of use and clarity of output.
# Other lookup tools tend to have less functionality than dig.

# Function to display information about subdomain
function get_subdomain_info() {
	local subdomain=$1
	local record_type=$(host $subdomain | awk '{print $5}')
	local destination=$(host $subdomain | awk '{print $6}')
	
	echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
	}

# Get the default subdomains
default_subdomains=(www lb-01 web-01 web-02)

# Get the arguments
domain=$1
subdomain=$2

# If the subdomain argument is not provided,
# get the information for the default subdomains
if [ -z "$subdomain" ]; then
	for subdomain in "${default_subdomains[@]}"; do
		get_subdomain_info "$subdomain"
	done
else
# Get the information for the specified subdomain
	get_subdomain_info "$subdomain"
fi
