#!/usr/bin/env bash

sudo apt update -y
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's|listen 80 default_server;|listen 80;|g' /etc/nginx/sites-available/default

# Create an index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

#Restart Nginx server
sudo service nginx restart
