#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update && sudo apt upgrade -y
sudo apt-get install -y nginx

# Create an index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Redirect_me/
sudo tee -i /etc/nginx/sites-available/default > /dev/null << EOF 
server {
	# Redirect to HTTPS
	listen	80;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	
	location /redirect_me {
		return 301 https://github.com/odoublea;
	}
EOF

# Link site-available to site-enabled
# ln -s /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default

#Restart Nginx server
sudo service nginx restart
