#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update && sudo apt upgrade -y
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 'listen 80 default_server/a rewrite ^/redirect_me https://github.com/odoublea/ permanent;' /etc/nginx/sites-available/default

#Restart Nginx server
sudo service nginx restart
