#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\t return 301 https:\/\/www.github.com\/odoublea;\n\t}|" /etc/nginx/sites-available/default
sudo service nginx start
