#!/usr/bin/env bash
# Configure your Nginx to have a custom 404 page

sudo apt update -y
sudo apt-get install -y nginx

# Configure Nginx to use the custom page
sudo sed -i 's/error_page 404 \/404.html;/error_page 404 \/custom_404.html;\n        location = \/custom_404.html {\n            internal;\n        }/' /etc/nginx/nginx.conf

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Restart Nginx
sudo service nginx restart
