#!/usr/bin/env bash
# Configure your Nginx to have a custom 404 page

sudo apt update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "s|server_name _;|server_name _;\n\tlocation /redirect_me {\n\t\t return 301 https:\/\/www.github.com\/odoublea;\n\t}|" /etc/nginx/sites-available/default
# Configure custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s|server_name _;|server_name _;\n\terror_page 404 404.html;|" /etc/nginx/sites-available/default
sudo service nginx restart
