#!/usr/bin/env bash
# Configure your Nginx to have a custom 404 page

sudo apt update && sudo apt upgrade -y

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx to use the custom page
sudo sed -i "s/error_page 404 \/404.html;/error_page 404 \/404.html;\n        location = \/404.html {\n            internal;\n        }/" /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
