#!/usr/bin/env bash
# Configure web-02 to be identical to web-01 and modify nginx.conf to have the custom HTTP header `X-Served-By`

sudo apt-get update && sudo apt-get upgrade install -y
sudo apt-get install nginx -y

sudo sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By $HOSTNAME;/" /etc/nginx/nginx.conf
# sudo sed -i '/http {/a\ add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
