#!/usr/bin/env bash
# Install and configure HAproxy on load-balancer

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy=2.6.\* -y

sudo cat << EOT >> /etc/default/haproxy
ENABLED=1
EOT

sudo bash -c 'cat << EOT >> /etc/haproxy/haproxy.cfg

frontend http-in
        bind *:80
        default_backend servers
backend servers
        balance roundrobin
        server 26887-web-01 54.165.180.170 check
        server 26887-web-02 54.210.123.212 check
EOT'

sudo service haproxy restart
