#!/usr/bin/env bash
# Install and configure HAproxy on load-balancer

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.6 -y
sudo apt-get install haproxy=2.6.\* -y
sudo apt-get update -y

sudo tee -a /etc/default/haproxy > /dev/null << EOT
ENABLED=1
EOT

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

MY_ID=26887

sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null << EOT

listen  $MY_ID-lb-01
        bind *:80
        balance roundrobin
        server $MY_ID-web-01 54.165.180.170:80 check
        server $MY_ID-web-02 54.210.123.212:80 check
EOT

sudo service haproxy restart
