#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer for web-01 and web-02
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*

MY_ID=26887

echo "
listen $MY_ID-lb-01
	bind *:80
	balance roundrobin
	server $MY_ID-web-01 54.165.180.170:80 check
	serevr $MY_ID-web-02 54.210.123.212:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
