#!/usr/bin/env bash
# Investigating why Nginx is not runnig on port 80

# Checked what port and IP nginx is listening to
# Discovered Nginx is listening to port 8080 instead of port 80
# Removed current settings
rm /etc/nginx/sites-enabled/default
# Link to Nginx default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# Restart nginx
sudo ufw allow 'Nginx HTTP'
service nginx restart
