#!/usr/bin/env bash
# Investigating why Nginx is not runnig on port 80

# Checked what port and IP nginx is listening to
netstat -lpn

# Discovered Nginx is listening to port 8080 instead of port 80
# Updated the /etc/nginx/sites-enabled/default to enable Nginx listen on port 80
sed -i "s|listen 8080 default_server|listen 80|g" /etc/nginx/sites-enabled/default
sed -i "s|listen \[::\]:8080 default_server ipv6only=on|listen \[::\]:80|g" /etc/nginx/sites-enabled/default

# Restart nginx
service nginx restart
