#!/usr/bin/env bash
#This script does a lot

echo "echo $$" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
done
trap "I hate the kill command" SIGTERM
trap "Y U no love me?!" SIGINT
rm -r /var/run/myscript.pid
