#!/usr/bin/env bash
# Displays numbers 1 to 100
#	multiples of 3 display "Fizz"
#	multiples of 5 display "Buzz"
#	multiples of 5 an 3 display "FizzBuzz"

for i in {1..100}
do
	if (( i % 3 == 0 && i % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( i % 3 == 0 ))
	then
		echo "Fizz"
	elif (( i % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done;
