#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

j=1
while [ $j -le 10 ]
do
	if [ $j -eq 4 ];
	then
		echo "bad luck"
	elif [ $j -eq 8 ];
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( j++ ))
done;
