#!/usr/bin/env bash
# This script prints minutes in each hour

hour=0;
while (( hour < 12 ))
do
	echo "Hour: $hour";
	minute=1;
	while (( minute <= 59 ))
	do
		echo "$minute";
		(( minute++ ))
	done
	(( hour++ ));
done
