#!/usr/bin/env bash
# Script that displays the content of the current directory
# in a list format with only the name after "-" displayed


list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2;
done;
